---
- name: Add 'docker' group
  group:
    name: docker
    state: present

- name: Add ansible_user to 'docker' group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  register: user_to_docker_group

- name: Start docker service
  import_tasks: start_service.yml

- name: Reset SSH connection so groups are available
  shell: sleep 1; pkill -u {{ ansible_user }} sshd
  async: 3
  poll: 2
  when: user_to_docker_group.changed
