---
- name: Add 'docker' group
  group:
    name: docker
    state: present

- name: Add ansible_user to 'docker' group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  register: user_to_docker_group

- name: Load 'docker' group into the ansible_user
  command: newgrp docker
  when: user_to_docker_group.changed

- name: Start docker service
  import_tasks: start_service.yml

